chore: Dockerfile調整

diff --git a/Dockerfile.dev-server b/Dockerfile.dev-server
--- a/Dockerfile.dev-server
+++ b/Dockerfile.dev-server
@@ -1,20 +1,51 @@
-FROM node:18 AS builder
+# NOTE: ref https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env
+
+# base stage
+FROM node:18-alpine3.17 AS base
+
+# deps stage
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
+RUN apk add g++ make py3-pip
 
 WORKDIR /app
-COPY package.json ./
-COPY package-lock.json ./
-RUN yarn install --frozen-lockfile --production=false
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# builder stage
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
+COPY .env.production .env.production
+
 RUN yarn build
 
-FROM node:16-stretch-slim AS runner
+# runner stage
+FROM base AS runner
+WORKDIR /app
+
 ENV NODE_ENV=production
 
-WORKDIR /app
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
 COPY package.json ./
 COPY package-lock.json ./
 RUN yarn install --frozen-lockfile --production=true
 COPY --from=builder /app/next.config.js ./
 COPY --from=builder /app/.next ./.next
 COPY --from=builder /app/public ./public
+
+# EXPOSE 3000
+
+# ENV PORT 3000
+# ENV HOSTNAME localhost
+
 CMD ["yarn", "cmd:start:dev"]
